#!/usr/bin/env python3
"""airx memdiff — deterministic worklist of what a commit changed vs what memory knows. No LLM, no tokens.

Scopes to the just-committed diff (default HEAD~1..HEAD):
  • enhance candidates = class/named-query symbols introduced by the commit that NO note mentions yet
  • drift             = note citations that no longer resolve (file:line dangling + unresolved symbols)
Writes ai_memory/PENDING-ENHANCEMENTS.md for /airx:enhance to consume. Skips merge & ai_memory-only commits.

    python3 memdiff.py <wiki-dir> [--range A..B]
Exit: 0 always.
"""
from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("airx_vc", HERE / "verify-citations.py")
vc = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(vc)


def git(repo: Path, *args) -> str:
    try:
        return subprocess.run(["git", "-C", str(repo), *args],
                              capture_output=True, text=True, timeout=30).stdout
    except Exception:
        return ""


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    rng = next((a.split("=", 1)[1] for a in sys.argv if a.startswith("--range=")), "HEAD~1..HEAD")
    if not args:
        print("usage: memdiff.py <wiki-dir> [--range=A..B]", file=sys.stderr)
        return 2
    wiki = Path(args[0]).resolve()
    if not wiki.is_dir():
        print(f"error: wiki {wiki} not found", file=sys.stderr)
        return 2
    repo = vc.repo_from_manifest(wiki)
    mem = wiki / "ai_memory"
    if repo is None or not repo.is_dir() or not mem.is_dir():
        print(f"AIRX MEMDIFF  cannot run (repo '{repo}' / ai_memory missing)")
        return 0

    # guard: skip merge commits (HEAD~1 ambiguous)
    if len(git(repo, "rev-list", "--parents", "-n1", "HEAD").split()) > 2:
        print("AIRX MEMDIFF  merge commit — skipped")
        return 0
    changed = [l for l in git(repo, "diff", "--name-only", rng).splitlines() if l.strip()]
    code = [f for f in changed if f.rsplit(".", 1)[-1].lower() in vc._CODE_EXTS and not f.startswith("ai_memory/")]
    if not code:
        print("AIRX MEMDIFF  no code changes in range — skipped")
        return 0

    notes = [p for p in sorted(mem.glob("**/*.md"))
             if not p.name.startswith("_") and p.name not in vc.NON_NOTES and ".cache" not in p.parts]
    note_text = "\n".join(p.read_text(errors="ignore") for p in notes)

    # enhance candidates: new symbols in changed files not mentioned anywhere in memory
    cand = set()
    for f in code:
        if f.endswith((".java", ".kt")):
            stem = Path(f).stem
            if stem not in note_text:
                cand.add(stem)
        elif f.endswith("queries.xml") or ("quer" in Path(f).name.lower() and f.endswith(".xml")):
            body = git(repo, "show", f"HEAD:{f}")
            for m in re.finditer(r'name="([^"]+)"', body):
                if m.group(1) not in note_text:
                    cand.add(m.group(1))

    # drift: dangling file:line + unresolved symbols across current notes (uses cached index)
    cw = vc.check_wiki(wiki)
    drift = [p for p in cw.get("problems", []) if "dangling" in p] + cw.get("sym_problems", [])

    out = mem / "PENDING-ENHANCEMENTS.md"
    lines = ["# Pending memory enhancements", "",
             f"> Auto-generated by `memdiff` from `{rng}`. Run **/airx:enhance** to fold these in (verified).",
             f"> Commit touched {len(code)} code file(s).", ""]
    lines.append("## Enhance candidates (in code, missing from memory)")
    lines += [f"- `{c}` — new/changed in this commit, not in any note" for c in sorted(cand)] or ["- none"]
    lines += ["", "## Drift (note claims that no longer resolve)"]
    lines += [f"- {d}" for d in drift[:40]] or ["- none"]
    if len(drift) > 40:
        lines.append(f"- …and {len(drift) - 40} more (run /airx:check for the full drift list)")
    out.write_text("\n".join(lines) + "\n")

    print(f"AIRX MEMDIFF  {wiki.name}  range {rng}")
    print(f"  code files changed: {len(code)}   enhance candidates: {len(cand)}   drift items: {len(drift)}")
    print(f"  → {out.name} written. Run /airx:enhance to fold in (verified).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
